### ISSUE TITLE
Case Conventions

### ISSUE THREAD

**Issue by Juddling** [netsells/code-standards#23]
* JSON responses: `snake_case`
* Databases names, tables, columns: `snake_case`
* URL parameters, `snake_case`: e.g. `/user/2/show?include_extra_info=true`
* [PSR-2](https://www.php-fig.org/psr/psr-2/) dictates the cases used in PHP code
* GitHub repos: `slug-case`

## Laravel Routes
* Names: `slug-case`
* URLs: `slug-case`

**Comment by spamoom** [comment]
@craigsansam
